version: '3'

services:
  backend:
    container_name: hs-backend
    build: .
    ports:
      - "5000:5000"

  elasticsearch: # Elasticsearch Instance
    container_name: hs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    volumes: # Persist Elasticsearch data in seperate volume named "esdata"
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports: # Expose Elasticsearch ports
      - "9200:9200"
      - "9300:9300"

volumes: # Define seperate volume for Elasticsearch data
  esdata: