version: "3.5"

services:
  hs-backend:
    container_name: hs-backend
    build: ./hs-backend
    ports:
      - "5000:5000"

  elasticsearch: # Elasticsearch Instance
    container_name: hs-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    volumes: # Persist Elasticsearch data in seperate volume named "esdata"
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS-Xms512m -Xmx512m"
    ports: # Expose Elasticsearch ports
      - "9200:9200"
      - "9300:9300"

volumes:
  esdata: