version: '3'

services:
  hs-backend:
    container_name: hs-backend
    build: .
    ports:
      - "5000:5000"

  hs-frontend:
    container_name: hs-frontend
    build: ./hs-frontend
    ports:
      - "8080:4200"

  hs-elk: # Elasticsearch Instance
    container_name: hs-elastic
    image: sebp/elk
    ports:
      - "9200:9200"
      - "5601:5601"
      - "5044:5044"