version: "3"

services:
  nginx:
    container_name: hs-nginx
    image: nginx
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - c:/users/jon/projekte/uni/HistoricalNewsSearch/hs-frontend/dist/hs-frontend:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    container_name: hs-backend
    restart: always
    build: ./hs-backend
    ports:
      - "5000:5000"
    volumes:
      - ./hs-backend:/usr/src/app
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    depends_on:
      - elasticsearch

  elasticsearch: # Elasticsearch Instance
    container_name: hs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    volumes: # Persist Elasticsearch data in seperate volume named "esdata"
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9200:9200"
      - "9300:9300"

volumes:
  esdata:
